### ISSUE TITLE
Assignment3

### ISSUE THREAD

**Issue by vkats-spbu** [Konstantinst128027/HomeAssignments#3]
<pre>victor@victor-VirtualBox:~/accesment/Konstantinst128027/HomeAssignments/Assignment3$ make
g++  -c armour.cpp -o armour.o
g++  -c Autobot.cpp -o Autobot.o
g++  -c decepticon.cpp -o decepticon.o
g++  -c main.cpp -o main.o
g++  -c minicon.cpp -o minicon.o
g++  -c transformer.cpp -o transformer.o
g++  -c weapon.cpp -o weapon.o
g++ -c gtest/gtest_armour.cpp -o gtest/gtest_armour.o
<b>gtest/gtest_armour.cpp:4:10:</b> <font color="#C01C28"><b>fatal error: </b></font>/home/konstbrat/Рабочий стол/main/Assignment3/armour.h: No such file or directory
    4 | #include <font color="#C01C28"><b>&quot;/home/konstbrat/Рабочий стол/main/Assignment3/armour.h&quot;</b></font>
      |          <font color="#C01C28"><b>^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~</b></font>
compilation terminated.
make: *** [Makefile:13: gtest/gtest_armour.o] Error 1
</pre>

**Comment by Konstantinst128027** [comment]
Здравствуйте! Я все исправил, можете проверить все!!!
 
 
--
Константин Березкин
Отправлено из Почты  Mail

**Comment by vkats-spbu** [comment]
Как так получилось, что заголовки оказались в директории с тестами?
Дело в том, что заголовки без их исходников бесполезны, также как и исходники без заголовков.
Если раскладываете по директориям, то принято исходники класть в src, заголовки в include и тесты в test

**Comment by Konstantinst128027** [comment]
Здравствуйте!!! Я все исправил. Посмотрите пожалуйста!!! Заранее спасибо!!
 
 
--
Константин Березкин
Отправлено из Почты  Mail
